# vim:set ft=yaml ts=2 sts=2 sw=2 et:
---
version: 0.2

phases:
  install:
    commands:
      - auto/install
  build:
    commands:
      - auto/build

artifacts:
  files:
    - out/*.template
    - out/*.parameters
  discard-paths: yes
